frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"
urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('flights/table/', views.FlightTableView.as_view(), name='flights_table'),
    path('flights/map/', views.FlightMapView.as_view(), name='flights_map'),
    path("flightdetail/<int:pk>/", views.FlightDetailView.as_view(), name="flight_detail"),
    path('stats/totals', views.StatsTotalsView.as_view(), name='totals'),
    path('stats/years', views.StatsYearsView.as_view(), name='years'),
    path('stats/places', views.StatsPlacesView.as_view(), name='places'),
    path('stats/evolution', views.StatsEvolutionView.as_view(), name='evolution'),
]

igc_lens/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("importer.urls")),
    path("", include("frontend.urls")),
] + debug_toolbar_urls()

frontend/models.py
from django.db import models

from importer.models import *

def empty_dict():
    return {}

#class UserSettings(models.Model):
#
#    # glide ratio, unit is 1 (meter/meter)
#    glide_rating_good = models.FloatField(default=10)
#    glide_rating_neutral = models.FloatField(default=7.5)
#    # else bad
#
#    # average vertical velocity, unit is m/s
#    thermal_rating_good = models.FloatField(default=2.0)
#    thermal_rating_neutral = models.FloatField(default=1.0)
#    # else bad
#    



class FlightFilter(models.Model):
    
    all = models.JSONField(default=empty_dict)
    active = models.JSONField(default=empty_dict)

    def add_default(self):
        self.all.update({
            "50km+": "xc_dist",
            "100km+": "xc_dist",
            "150km+": "xc_dist",
            "200km+": "xc_dist",
            "250km+": "xc_dist",
            "1h+": "airtime",
            "3h+": "airtime",
            "5h+": "airtime",
            "7h+": "airtime",
            "Closed FAI Triangle": "scoring_name",
            "Closd Free Triangle": "scoring_name",
            "FAI Triangle": "scoring_name",
            "Free Triangle": "scoring_name",
            "Free Distance": "scoring_name",
        })
        # todo
        # No database takeoff

    def add_takeoffs(self):
        """Add unique list of takeoffs"""
        for x in Flight.objects.all().get_unique_takeoffs():
            self.all[x] = 'takeoff'

    def set_filter(self,name):
        """Copy to active filter set"""
        if name in self.all:
            self.active[name] = self.all[name]
            self.save()

frontend/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

# https://docs.djangoproject.com/en/5.1/ref/class-based-views/
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

import json
import re

# project
from importer.models import *
from frontend.models import *


class HomepageView(TemplateView):
    template_name = "frontend/homepage.html"


class StatsTotalsView(TemplateView):
    template_name = "frontend/stats_totals.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        # get total values over all flights
        total = {}
        total["flights"] = fm.all().count()
        total["airtime"] = fm.all().get_airtime()
        total["xc_km"] = fm.all().get_xckm()
        total["takeoffs"] = len(fm.all().get_unique_takeoffs())
        total["states"] = len(fm.all().get_unique_states())
        total["countries"] = len(fm.all().get_unique_countries())
        total["years"] = len(fm.all().get_unique_years())
        total["days"] = len(fm.all().get_unique_days())
        
        context["total"] = total
        return context


class StatsYearsView(TemplateView):
    template_name = "frontend/stats_years.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        
        per_year = {}
        for y in fm.all().get_unique_years():
            qy = fm.all().filt_year(y)
            per_year[y] = {"airtime": {"abs": 0, "rel": 0},
                           "flights": {"abs": 0, "rel": 0},
                           "xc_km": {"abs": 0, "rel": 0},
                           "days":  {"abs": 0, "rel": 0},}
            per_year[y]["airtime"]["abs"] = qy.get_airtime()
            per_year[y]["flights"]["abs"] = qy.count()
            per_year[y]["xc_km"]["abs"] = qy.get_xckm()
            per_year[y]["days"]["abs"] = len(qy.get_unique_days())
        
        # compute values relative to best year
        for field in ["airtime", "flights","xc_km","days"]:
            m = max(item[field]["abs"] for item in per_year.values())
            for item in per_year.values():
                # in percent for use in CSS
                item[field]["rel"] = 100 * item[field]["abs"] / m
        
        context["per_year"] = per_year
        return context


class StatsPlacesView(TemplateView):
    template_name = "frontend/stats_places.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        
        per_takeoff = {}
        for y in fm.all().get_unique_takeoffs():
            qy = fm.all().filt_takeoff(y)
            per_takeoff[y] = {"airtime": 0,"flights": 0,"xc_km": 0}
            per_takeoff[y]["airtime"] = qy.get_airtime()
            per_takeoff[y]["flights"] = qy.count()
            per_takeoff[y]["xc_km"] = qy.get_xckm()
        # Sort the dictionary by the 'airtime' value of the inner dictionaries
        per_takeoff = dict(sorted(per_takeoff.items(), 
                                  key=lambda item: item[1]['airtime'],
                                  reverse=True)) # descending

        per_state = {}
        for y in fm.all().get_unique_states():
            qy = fm.all().filt_state(y)
            per_state[y] = {"airtime": 0,"flights": 0,"xc_km": 0}
            per_state[y]["airtime"] = qy.get_airtime()
            per_state[y]["flights"] = qy.count()
            per_state[y]["xc_km"] = qy.get_xckm()
        # Sort the dictionary by the 'airtime' value of the inner dictionaries
        per_state = dict(sorted(per_state.items(), 
                                key=lambda item: item[1]['airtime'],
                                reverse=True)) # descending
        
        context["per_takeoff"] = per_takeoff
        context["per_state"] = per_state
        return context


class StatsEvolutionView(TemplateView):
    template_name = "frontend/stats_evolution.html"


class FlightDetailView(generic.DetailView):
    """Detail view of one flight, includes map and textual data"""
    model = Flight
    template_name = "frontend/flight_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ensure correct booleans for JS, true vs True in python
        d = self.object.xcscore.geojson
        context["xcscore_layer"] = json.dumps(d)
        # map bounding box
        lat = self.object.timeseries['lat']
        lon = self.object.timeseries['lon']
        context["corner_NE"] = [max(lat),max(lon)]
        context["corner_SW"] = [min(lat),min(lon)]
        # takeoff 
        o = self.object.takeoff
        if o.name: # database match
            context["takeoff"] = f"{o.name}"
        else:
            context["takeoff"] = f"{o.idstr} (not in DB)"
        
        return context
    

class FlightListView(ListView):
    """A table where each flight is a row"""
    model = Flight
    context_object_name = 'flights'

    def get_queryset(self):
        qs = super().get_queryset()
        for value, filter in FlightFilter.objects.get().active.items():
            
            if filter == 'takeoff':
                qs = qs.filt_takeoff(value)

            if filter == 'xc_dist':
                # extract number
                match = re.search(r'\d+', value)
                qs = qs.filter(xcscore__distance__gt=int(match.group()))

            if filter == 'airtime':
                match = re.search(r'\d+', value)
                sec = 3600*int(match.group()) # hours to sec
                qs = qs.filter(airtime__gt=sec)

            if filter == 'scoring_name':
                qs = qs.filter(xcscore__scoringName=value)

        # todo: order-by via table headings
        return qs.order_by('-date')

    def get(self, request, *args, **kwargs):
        # accumulate filters in FlightFilter model
        if 'flightFilter' in request.GET:
            filter_verbose_name = request.GET.get('flightFilter')
            FlightFilter.objects.get().set_filter(filter_verbose_name)
        # reset FlightFilter model
        if 'reset' in request.GET:
            o = FlightFilter.objects.get()
            o.active = {}
            o.save()

        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # todo: get FlightFilter for current user
        filter = FlightFilter.objects.get()
        context['filter_all'] = list(filter.all)
        context['filter_active'] = list(filter.active)    
        return context


class FlightTableView(FlightListView):
    """A classic table"""
    template_name = "frontend/flights_table.html"
    paginate_by = 50 # todo: setting

    #def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    rows = context['object_list']  # Your rows data
    #    # Loop through your rows and assign icons based on marker type
    #    for row in rows:
    #        # add fields to row
    #    return context

class FlightMapView(FlightListView):
    """A map where each flight is represented as marker"""
    template_name = "frontend/flights_map.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = self.get_queryset()
        # icon at takeoff location
        context["marker_list"] = [f.takeoff_marker() for f in qs]
        # map bounding box
        if qs:
            lat = qs.values_list('takeoff__lat', flat=True)
            lon = qs.values_list('takeoff__lon', flat=True)
            context["corner_NE"] = [max(lat),max(lon)]
            context["corner_SW"] = [min(lat),min(lon)]
        else:
            # ain't nothing to show
            context["corner_NE"] = [-48.875486, -123.392519]
            context["corner_SW"] = [-48.875486, -123.392519]

        return context

frontend/templates/frontend/details_accordion.html
<div class="accordion accordion-flush" id="accordion">
  <!--<div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        heading
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordion">
      <div class="accordion-body">
      </div>
    </div>
  </div>-->
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
        Takeoff and Landing
      </button>
    </h2>
    <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordion">
      <div class="accordion-body">
        <p>Airtime {{flight.airtime_str}}</p>
        <h6>Takeoff</h6>
        <ul>
          {% with flight.takeoff.datetime_local as lt %}
          <li>{{ lt.time }} <small style="font-size: 60%" class="text-muted">UTC{{ lt.utc_delta }}</small></li>
          {% endwith %}
          <li>{{takeoff}}</li>
          {%if flight.takeoff.name%}
          <li>{{flight.takeoff.dist|floatformat}} m from database takeoff location</li>
          {%endif%}
        </ul>
      <h6>Landing</h6>
        <ul>
          {% with flight.landing.datetime_local as lt %}
          <li>{{ lt.time }} <small style="font-size: 60%" class="text-muted">UTC{{ lt.utc_delta }}</small></li>
          {% endwith %}
          <li>TODO m from takeoff</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
        Thermals and Glides
      </button>
    </h2>
    <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordion">
      <div class="accordion-body">
        <p>Turn direction ratio: left-mix-right
        <div class="progress-stacked">
          <div class="progress" role="progressbar" style="width:{% widthratio flight.thermals.circ_dir_L 1 100 %}%">
            <div class="progress-bar bg-info">{{flight.thermals.circ_dir_L|floatformat:2}}</div>
          </div>
          <div class="progress" role="progressbar" style="width:{% widthratio flight.thermals.circ_dir_LR 1 100 %}%">
            <div class="progress-bar bg-warning">{{flight.thermals.circ_dir_LR|floatformat:2}}</div>
          </div>
          <div class="progress" role="progressbar" style="width:{% widthratio flight.thermals.circ_dir_R 1 100 %}%">
            <div class="progress-bar">{{flight.thermals.circ_dir_R|floatformat:2}}</div>
          </div>
        </div>
        </p>
        <p>Thermal to glide ratio
        <div class="progress-stacked">
          <div class="progress" role="progressbar" style="width:{% widthratio flight.thermals.time_total 1 100 %}%">
            <div class="progress-bar bg-info">{{flight.thermals.time_total|floatformat:2}}</div>
          </div>
          <div class="progress" role="progressbar" style="width:{% widthratio flight.glides.time_total 1 100 %}%">
            <div class="progress-bar bg-warning">{{flight.glides.time_total|floatformat:2}}</div>
          </div>
        </div>
        </p>
        <p>
          <li>Maximum average climb {{flight.thermals.max_avg_climb|floatformat}} m/s</li>
          <li>Maximum gain {{flight.thermals.max_gain|floatformat}} m</li>
          <li>Average speed of glide sections: {{flight.glides.avg_speed|floatformat:2}} km/h</li>
        </p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
        XC Score
      </button>
    </h2>
    <div id="flush-collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordion">
      <div class="accordion-body">
        <h6>{{flight.xcscore.distance}} km {{ flight.xcscore.scoringName }}</h6>
        <ul>
          <li>Multiplier {{flight.xcscore.multiplier}} x</li>
          <li>Closing Distance (Penalty) {{flight.xcscore.closingDistance|default:0}} km</li>
          <li>{{flight.xcscore.score}} points</li>
        </ul>
        <h6>Legs</h6>
        <table class="table table-borderless"><tbody>
        {%for leg in flight.xcscore.legs%}  
        <tr><td>{{leg.name}}</td><td>{{leg.distance}} km</td><td>hh:mm</td><td>todo km/h</td></tr>
        {%endfor%}
        </tbody></table>
        <h6>Speed</h6>
        <ul>
          <li>{{flight.xcscore.xc_speed_airtime|floatformat}} km/h airtime total </li>
          <li>todo km/h route duration</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
        Hardware
      </button>
    </h2>
    <div id="flush-collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordion">
      <div class="accordion-body">
        <h6>Glider type</h6>
        <ul>
          <li>{{ flight.glider|default:"None set"}}</li>
        </ul>
        <h6>Flight recorder</h6>
        <ul>
          <li>Type: {{flight.recorder.type}}</li>
          <li>Manufacturer code: {{flight.recorder.code}}</li>
          <li>GNSS sensor: {{flight.recorder.gnss}}</li>
          <li>Pressure sensor: {{flight.recorder.press}}</li>
          <li>Firmware version: {{flight.recorder.firmware_v}}</li>
          <li>Hardware version: {{flight.recorder.hardware_v}}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

frontend/templates/frontend/flight_detail.html
{% extends "main.html" %}
{% block head %}
<link rel="stylesheet" 
href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
crossorigin=""/>
<style>
html, body {
    height: 100%; /* Make sure the body and html are 100% height */
}
body {
    display: flex;
    flex-direction: column; /* Enable flexbox on body */
}
.container-fluid {
    flex-grow: 1; /* Make the container take up remaining space */
    position: relative; /* Ensures that the button is positioned relative to this container */
}
.offcanvas-body {
    --bs-offcanvas-padding-y: 0;
    --bs-offcanvas-padding-x: 0;
}
</style>
{% endblock %}


{% block detail_button %}
<button class="btn btn-primary floating-btn" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample">
    Details
</button>
{% endblock %}


{% block content %}
<!-- leaflet container -->
<div class="container-fluid d-flex align-items-center justify-content-center p-0">
    <div id="map" style="width: 100%; height: 100%;"></div>
</div>
<!-- Off-Canvas Component -->
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Flight Details</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas"></button>
  </div>
  <div class="offcanvas-body">
  <!-- Off-Canvas Body -->
  {% include "frontend/details_accordion.html" %}
</div>
<!-- leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin="">
</script>
<!-- leaflet map -->
{% load static %}
<script src="{% static 'flight_detail_map.js' %}"></script>
<script>
    const cornerNE = {{corner_NE|safe}};
    const cornerSW = {{corner_SW|safe}};
    const geoGlides = {{ flight.glides.geojson | safe }};
    const geoThermals = {{ flight.thermals.geojson | safe }};
    const geoXcscore = {{ xcscore_layer | safe }};
    // Initialize map if the map container exists
    if (document.getElementById('map')) {
      mapThemeInterface.initMap(
        cornerNE,
        cornerSW,
        geoGlides,
        geoThermals,
        geoXcscore);
    }
</script>
{% endblock %}

frontend/templates/frontend/flight_list.html
{% extends "main.html" %}
{% block content %}
<!-- Pagination controls -->
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for k in page_obj.paginator.page_range %}
            {% if page_obj.number == k %}
            <li class="page-item active">
            {% else %}
            <li class="page-item">
            {% endif %}
                <a class="page-link" href="?page={{ k }}">{{ k }}</a>
            </li>
        {% endfor %}
    </ul>
</nav>
{% if flights %}

<h2>Flights</h2>
<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th>Date</th>
      <th>TO (UTC)</th>
      <th>Airtime</th>
      <th>Country</th>
      <th>Takeoff</th>
      <th>XC Points</th>
      <th>ID</th>
    </tr>
  </thead>
  <tbody>
    {% for flight in flights %}
    <tr>
        <td>{{ flight.takeoff.time.date }}</td>
        <td>{{ flight.takeoff.time|time:"H:i" }}</td>
        <td>{{ flight.airtime_str }}</td>
        <td>{{ flight.takeoff.country|upper }}</td>
        <td>{{ flight.takeoff.name|default:"N/A" }}</td>
        <td>{{ flight.xcscore.score|floatformat:0 }}</td>
        <td><a href="{% url 'frontend:flight_detail' flight.id %}">{{ flight.file_hash_short}}</a></td>
        </a>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}
    <p>No flights in DB.</p>
{% endif %}

{% endblock %}

frontend/templates/frontend/flights_map.html
{% extends "main.html" %}


{% block nav_filter %}
{% include "filter_form.html" %}
{% endblock %}


{% block head %}
<link rel="stylesheet" 
href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
crossorigin=""/>
<style>
html, body {
    height: 100%; /* Make sure the body and html are 100% height */
}
body {
    display: flex;
    flex-direction: column; /* Enable flexbox on body */
}
.container-fluid {
    flex-grow: 1; /* Make the container take up remaining space */
    position: relative; /* Ensures that the button is positioned relative to this container */
}
.filter-div {
    position: absolute;
    top: 15px;
    right: 50%;
    transform: translateX(+50%); /* simulate anchor at center */
    z-index: 1039; /* https://getbootstrap.com/docs/5.3/layout/z-index/ */
}
.center-overlay-div {
    position: absolute;
    top: 50%;
    right: 50%;
    transform: translateX(+50%); /* simulate anchor at center */
    z-index: 1039;
}
</style>
{% endblock %}


{% block content %}
<!-- leaflet container -->
<div class="container-fluid d-flex align-items-center justify-content-center p-0">
    <div id="map" style="width: 100%; height: 100%;"></div>
    <!-- active filters overlay -->
    {%if filter_active%}
    <div class="filter-div">
        {% for item in filter_active %}
        <span class="badge text-bg-warning">{{item}}</span>
        {% endfor %}
    </div>
    {%endif%}
    {%if not flights%}
    <div class="center-overlay-div">
        here be dragons
    </div>
    {%endif%}
</div>
<!-- leaflet -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin="">
</script>
<!-- leaflet map -->
{% load static %}
<script src="{% static 'map_markers.js' %}"></script>
<script>
    // Marker data
    const markerList = {{ marker_list|safe }};
    // map bounding box
    const cornerNE = {{corner_NE|safe}};
    const cornerSW = {{corner_SW|safe}};
    // Initialize map if the map container exists
    if (document.getElementById('map')) {
      mapThemeInterface.initMap(markerList,cornerNE,cornerSW);
    }
</script>
{% endblock %}

frontend/templates/frontend/flights_table.html
{% extends "main.html" %}
{% load static %}


{% block nav_filter %}
{% include "filter_form.html" %}
{% endblock %}


{% block content %}
<!-- filter div -->
<div class="container-md p-3" style="text-align: center;">
  {% for item in filter_active %}
  <span class="badge text-bg-warning">{{item}}</span>
  {% endfor %}
</div>
<!-- table div -->
<div class="container-md">
  {% if flights %}
  <table class="table table-hover table-sm w-100" style="max-width: 768px; margin: 0 auto;">
    <thead>
      <tr>
        <th><!--link icon--></th>
        <th>Takeoff Local Time <small style="font-size: 60%" class="text-muted">UTC +/-</small></th>
        <th>Takeoff Location</th>
        <th>Airtime</th>
        <th>XC km</th>
      </tr>
    </thead>
    <tbody>
      {% for flight in flights %}
      <tr>
        <td><a class="icon-link" href="{% url 'frontend:flight_detail' flight.id %}"><i class="bi-box-seam"></i></a></td>
        {% with flight.takeoff.datetime_local as lt %}
        <td>{{ lt.time }} <small style="font-size: 60%" class="text-muted">{{ lt.utc_delta }}</small></td>
        {% endwith %}
        <td>{%if flight.takeoff.name %} {{ flight.takeoff.name }} {% else %}<em>{{ flight.takeoff.idstr }}</em>{% endif %}</td>
        <td>{{ flight.airtime_str }}</td>
        <td style="display: flex; justify-content: left;">
          <img src="{%static flight.icon_url%}" alt="{{ flight.xcscore.scoringName }}">
          <span style="margin-left: 5px;"></span>{{ flight.xcscore.distance|floatformat:1 }}</span>
        </td>
        </a>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <!-- Pagination controls -->
  <div class="m-3">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
          {% for k in page_obj.paginator.page_range %}
            {% if page_obj.number == k %}
            <li class="page-item active">
            {% else %}
            <li class="page-item">
            {% endif %}
                <a class="page-link" href={% querystring page=k %}>{{ k }}</a> 
            </li>
          {% endfor %}
      </ul>
    </nav>
  </div> 
{% else %}
  <p><i class="bi-cloud-hail"></i> No flights in query.</p>
{% endif %}
</div>
{% endblock %}

frontend/templates/frontend/home.html
{% extends "main.html" %}

{% block content %}
<div class="container-lg mt-5">
    <div class="col-xl-10 offset-xl-1">

<h1>Total</h1>
<div class="row"><div class="col-6">
<p class="lead">
    You left the ground {{total.flights}} times for a total of 
    {{total.airtime|floatformat}} hours. Yay!
</p>
</div></div>

<h1>Per Year</h1>
<h2>Airtime</h2>
{% for year, vals in per_year.items %}
<div class="row">
    <div class="col-1">
        {{year}}
    </div>
    <div class="col-11">
        <div class="progress" 
             role="progressbar">
            <div class="progress-bar" style="width: {{ vals.airtime.rel }}%"> 
                {{ vals.airtime.abs|floatformat }} h 
            </div>
        </div>
    </div>
</div>
{% endfor %}

<h2>Number of Flights</h2>
{% for year, vals in per_year.items %}
<div class="row">
    <div class="col-1">
        {{year}}
    </div>
    <div class="col-11">
        <div class="progress" 
             role="progressbar">
            <div class="progress-bar" style="width: {{ vals.flights.rel }}%">
                {{ vals.flights.abs|floatformat }}
            </div>
        </div>
    </div>
</div>
{% endfor %}

</div></div>
{% endblock %}

frontend/templates/frontend/homepage.html
{% extends "main.html" %}

{% block head %}
{% endblock %}

{% block navbar %}
{% endblock %}

frontend/templates/frontend/stats_evolution.html
{% extends "main.html" %}

{% block content %}
<div class="container-lg mt-5">
</div>
{% endblock %}