frontend/urls.py
from django.urls import path
from . import views

app_name = "frontend"
urlpatterns = [
    path('', views.HomepageView.as_view(), name='homepage'),
    path('flights/table/', views.FlightTableView.as_view(), name='flights_table'),
    path('flights/map/', views.FlightMapView.as_view(), name='flights_map'),
    path("flightdetail/<int:pk>/", views.FlightDetailView.as_view(), name="flight_detail"),
    path('stats/totals', views.StatsTotalsView.as_view(), name='totals'),
    path('stats/years', views.StatsYearsView.as_view(), name='years'),
    path('stats/places', views.StatsPlacesView.as_view(), name='places'),
    path('stats/evolution', views.StatsEvolutionView.as_view(), name='evolution'),
]

igc_lens/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("importer.urls")),
    path("", include("frontend.urls")),
] + debug_toolbar_urls()

importer/urls.py
from django.urls import path
from . import views

app_name = "importer"
urlpatterns = [
    path('upload/', views.FileUpload.as_view(), name='upload'),
]

frontend/models.py
from django.db import models

from importer.models import *

def empty_dict():
    return {}

#class UserSettings(models.Model):
#
#    # glide ratio, unit is 1 (meter/meter)
#    glide_rating_good = models.FloatField(default=10)
#    glide_rating_neutral = models.FloatField(default=7.5)
#    # else bad
#
#    # average vertical velocity, unit is m/s
#    thermal_rating_good = models.FloatField(default=2.0)
#    thermal_rating_neutral = models.FloatField(default=1.0)
#    # else bad
#    



class FlightFilter(models.Model):
    
    all = models.JSONField(default=empty_dict)
    active = models.JSONField(default=empty_dict)

    def add_default(self):
        self.all.update({
            "50km+": "xc_dist",
            "100km+": "xc_dist",
            "150km+": "xc_dist",
            "200km+": "xc_dist",
            "250km+": "xc_dist",
            "1h+": "airtime",
            "3h+": "airtime",
            "5h+": "airtime",
            "7h+": "airtime",
            "Closed FAI Triangle": "scoring_name",
            "Closd Free Triangle": "scoring_name",
            "FAI Triangle": "scoring_name",
            "Free Triangle": "scoring_name",
            "Free Distance": "scoring_name",
        })
        # todo
        # No database takeoff

    def add_takeoffs(self):
        """Add unique list of takeoffs"""
        for x in Flight.objects.all().get_unique_takeoffs():
            self.all[x] = 'takeoff'

    def set_filter(self,name):
        """Copy to active filter set"""
        if name in self.all:
            self.active[name] = self.all[name]
            self.save()

frontend/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

# https://docs.djangoproject.com/en/5.1/ref/class-based-views/
from django.views import generic
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView

import json
import re

# project
from importer.models import *
from frontend.models import *


class HomepageView(TemplateView):
    template_name = "frontend/homepage.html"


class StatsTotalsView(TemplateView):
    template_name = "frontend/stats_totals.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        # get total values over all flights
        total = {}
        total["flights"] = fm.all().count()
        total["airtime"] = fm.all().get_airtime()
        total["xc_km"] = fm.all().get_xckm()
        total["takeoffs"] = len(fm.all().get_unique_takeoffs())
        total["states"] = len(fm.all().get_unique_states())
        total["countries"] = len(fm.all().get_unique_countries())
        total["years"] = len(fm.all().get_unique_years())
        total["days"] = len(fm.all().get_unique_days())
        
        context["total"] = total
        return context


class StatsYearsView(TemplateView):
    template_name = "frontend/stats_years.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        
        per_year = {}
        for y in fm.all().get_unique_years():
            qy = fm.all().filt_year(y)
            per_year[y] = {"airtime": {"abs": 0, "rel": 0},
                           "flights": {"abs": 0, "rel": 0},
                           "xc_km": {"abs": 0, "rel": 0},
                           "days":  {"abs": 0, "rel": 0},}
            per_year[y]["airtime"]["abs"] = qy.get_airtime()
            per_year[y]["flights"]["abs"] = qy.count()
            per_year[y]["xc_km"]["abs"] = qy.get_xckm()
            per_year[y]["days"]["abs"] = len(qy.get_unique_days())
        
        # compute values relative to best year
        for field in ["airtime", "flights","xc_km","days"]:
            m = max(item[field]["abs"] for item in per_year.values())
            for item in per_year.values():
                # in percent for use in CSS
                item[field]["rel"] = 100 * item[field]["abs"] / m
        
        context["per_year"] = per_year
        return context


class StatsPlacesView(TemplateView):
    template_name = "frontend/stats_places.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Flight object manager shortcut
        fm = Flight.objects        
        # catch empty flight db
        if not fm.count():
            return {}
        
        per_takeoff = {}
        for y in fm.all().get_unique_takeoffs():
            qy = fm.all().filt_takeoff(y)
            per_takeoff[y] = {"airtime": 0,"flights": 0,"xc_km": 0}
            per_takeoff[y]["airtime"] = qy.get_airtime()
            per_takeoff[y]["flights"] = qy.count()
            per_takeoff[y]["xc_km"] = qy.get_xckm()
        # Sort the dictionary by the 'airtime' value of the inner dictionaries
        per_takeoff = dict(sorted(per_takeoff.items(), 
                                  key=lambda item: item[1]['airtime'],
                                  reverse=True)) # descending

        per_state = {}
        for y in fm.all().get_unique_states():
            qy = fm.all().filt_state(y)
            per_state[y] = {"airtime": 0,"flights": 0,"xc_km": 0}
            per_state[y]["airtime"] = qy.get_airtime()
            per_state[y]["flights"] = qy.count()
            per_state[y]["xc_km"] = qy.get_xckm()
        # Sort the dictionary by the 'airtime' value of the inner dictionaries
        per_state = dict(sorted(per_state.items(), 
                                key=lambda item: item[1]['airtime'],
                                reverse=True)) # descending
        
        context["per_takeoff"] = per_takeoff
        context["per_state"] = per_state
        return context


class StatsEvolutionView(TemplateView):
    template_name = "frontend/stats_evolution.html"


class FlightDetailView(generic.DetailView):
    """Detail view of one flight, includes map and textual data"""
    model = Flight
    template_name = "frontend/flight_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ensure correct booleans for JS, true vs True in python
        d = self.object.xcscore.geojson
        context["xcscore_layer"] = json.dumps(d)
        # map bounding box
        lat = self.object.timeseries['lat']
        lon = self.object.timeseries['lon']
        context["corner_NE"] = [max(lat),max(lon)]
        context["corner_SW"] = [min(lat),min(lon)]
        # takeoff 
        o = self.object.takeoff
        if o.name: # database match
            context["takeoff"] = f"{o.name}"
        else:
            context["takeoff"] = f"{o.idstr} (not in DB)"
        
        return context
    

class FlightListView(ListView):
    """A table where each flight is a row"""
    model = Flight
    context_object_name = 'flights'

    def get_queryset(self):
        qs = super().get_queryset()
        for value, filter in FlightFilter.objects.get().active.items():
            
            if filter == 'takeoff':
                qs = qs.filt_takeoff(value)

            if filter == 'xc_dist':
                # extract number
                match = re.search(r'\d+', value)
                qs = qs.filter(xcscore__distance__gt=int(match.group()))

            if filter == 'airtime':
                match = re.search(r'\d+', value)
                sec = 3600*int(match.group()) # hours to sec
                qs = qs.filter(airtime__gt=sec)

            if filter == 'scoring_name':
                qs = qs.filter(xcscore__scoringName=value)

        # todo: order-by via table headings
        return qs.order_by('-date')

    def get(self, request, *args, **kwargs):
        # accumulate filters in FlightFilter model
        if 'flightFilter' in request.GET:
            filter_verbose_name = request.GET.get('flightFilter')
            FlightFilter.objects.get().set_filter(filter_verbose_name)
        # reset FlightFilter model
        if 'reset' in request.GET:
            o = FlightFilter.objects.get()
            o.active = {}
            o.save()

        return super().get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # todo: get FlightFilter for current user
        filter = FlightFilter.objects.get()
        context['filter_all'] = list(filter.all)
        context['filter_active'] = list(filter.active)    
        return context


class FlightTableView(FlightListView):
    """A classic table"""
    template_name = "frontend/flights_table.html"
    paginate_by = 50 # todo: setting

    #def get_context_data(self, **kwargs):
    #    context = super().get_context_data(**kwargs)
    #    rows = context['object_list']  # Your rows data
    #    # Loop through your rows and assign icons based on marker type
    #    for row in rows:
    #        # add fields to row
    #    return context

class FlightMapView(FlightListView):
    """A map where each flight is represented as marker"""
    template_name = "frontend/flights_map.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        qs = self.get_queryset()
        # icon at takeoff location
        context["marker_list"] = [f.takeoff_marker() for f in qs]
        # map bounding box
        if qs:
            lat = qs.values_list('takeoff__lat', flat=True)
            lon = qs.values_list('takeoff__lon', flat=True)
            context["corner_NE"] = [max(lat),max(lon)]
            context["corner_SW"] = [min(lat),min(lon)]
        else:
            # ain't nothing to show
            context["corner_NE"] = [-48.875486, -123.392519]
            context["corner_SW"] = [-48.875486, -123.392519]

        return context

frontend/templates/filter_form.html
<li class="py-2 py-lg-1 px-lg-1 col-12 col-lg-auto">
  <form class="d-flex" role="search" method="GET">
    <input class="form-control me-2" type="search" list="datalistOptions" id="flightFilter" name="flightFilter" placeholder="Filter">
      <datalist id="datalistOptions">
      {% for option in filter_all %}
        <option value="{{option}}">
      {%endfor%}
      </datalist>
    <button class="btn btn-outline-success me-2" name="apply" type="submit">Apply</button>
    <button class="btn btn-outline-secondary position-relative" name="reset" type="submit">Reset
      {%if filter_active%}
      <span class="position-absolute top-0 start-100 translate-middle p-2 bg-warning border border-light rounded-circle">
        <span class="visually-hidden">Filter active</span>
      </span>
      {%endif%}
    </button>
  </form>
</li>
<!-- separator -->
<li class="nav-item py-2 py-lg-1 col-12 col-lg-auto">
  <div class="vr d-none d-lg-flex h-100 mx-lg-2 text-white"></div>
  <hr class="d-lg-none my-2 text-white-50">
</li>

frontend/templates/main.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>igc lens</title>
  <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous">
  <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <!-- own stuff -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'colors.css' %}">
  <script src="{% static 'colormode.js' %}"></script>
  <!-- bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
    crossorigin="anonymous"></script>
  <!-- block head -->
  {% block head %}
  {% endblock %}
</head>
<body>
{% include "svg.html" %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'frontend:homepage' %}">igc lens</a>
    {% block detail_button %}
    {% endblock %}
    <!-- the burger-button appears when the div collapses -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapseLeft">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapseLeft">
      <!-- align left -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link" href="{% url 'frontend:flights_table' %}">Table</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'frontend:flights_map' %}">Map</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button">Statistics</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'frontend:totals' %}">Totals</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:years' %}">Years</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:places' %}">Places</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:evolution' %}">Evolution</a></li>
          </ul>
        </li>
        <li class="nav-item"><a class="nav-link" href="{% url 'importer:upload' %}">Upload</a></li>
      </ul>
      <!-- align center -->
      <!-- align right -->
      <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
        {% block nav_filter %}
        {% endblock %}
        <!-- theme selector -->
        <li class="nav-item dropdown">
          <button class="btn btn-link nav-link py-2 px-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme (dark)">
            <svg class="bi my-1 theme-icon-active"><use href="#moon-stars-fill"></use></svg>
            <span class="d-lg-none ms-2" id="bd-theme-text">Toggle theme</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-theme-text">
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                <svg class="bi me-2 opacity-50"><use href="#sun-fill"></use></svg>
                Light
                <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="dark" aria-pressed="true">
                <svg class="bi me-2 opacity-50"><use href="#moon-stars-fill"></use></svg>
                Dark
                <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="auto" aria-pressed="false">
                <svg class="bi me-2 opacity-50"><use href="#circle-half"></use></svg>
                Auto
                <svg class="bi ms-auto d-none"><use href="#check2"></use></svg>
              </button>
            </li>
          </ul>
        </li>
        <!-- user menu -->
        <li class="nav-item dropdown">
          <button class="btn btn-link nav-link py-2 px-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme (dark)">
            <svg class="bi my-1 theme-icon-active"><use href="#person-circle"></use></svg>
            <span class="d-lg-none ms-2" id="bd-theme-text">User</span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-theme-text">
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                Settings
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
                Logout
              </button>
            </li>
          </ul>
        </li>
        <!-- /user menu -->
      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

frontend/templates/svg.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
  </symbol>
  <symbol id="person-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
  </symbol>
</svg>